{% set name = "geostatista" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/geostatista/archive/{{ version }}.tar.gz
  sha256: 637c0f47690aa86dae8185ffaa1e2b208e302e22d6764320e8581eaa56d3e536

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.11
    - pip >=22.3.1
  run:
    - python >=3.9,<3.11
    - numpy ==1.23.5
    - pip >=22.3.1
    - statista >=0.1.7
    - pyramids >=0.2.11
    - loguru >=0.6.0

test:
  imports:
    - geostatista

about:
  home: https://github.com/MAfarrag/geostatista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Geo-spatial statistical package
  description: |
    Geo-spatial statistical package.
  dev_url: https://github.com/MAfarrag/geostatista
  doc_url: https://geostatista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/geostatista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
