{% set name = "geostatista" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 058764925777cfe9330e67d0f8db12bdb2a107c8e8a1601968e04ed2332c13d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=80.0.0
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - scipy >=1.10.0
    - geopandas >=1.0.0
    - pyramids >=0.46.0
    - loguru >=0.7.3

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - geostatista
  commands:
    - pip check

about:
  home: https://github.com/serapeum-org/geostatista
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Geo-spatial statistical package
  description: |
    Geo-spatial statistical package.
  dev_url: https://github.com/serapeum-org/geostatista
  doc_url: https://serapeum-org.github.io/geostatista/
  doc_source_url: https://github.com/serapeum-org/geostatista/blob/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
