{% set name = "geostatista" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/geostatista/archive/{{ version }}.tar.gz
  sha256: 3cde54dfda164237dd7aaaa7c3c552397c382e12692d70f861f21a9fa69943b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9.1,<3.10
    - pip >=22.2.2
  run:
    - python  >=3.9.1,<3.10
    - pip >=22.2.2
    - numpy >=1.21.2,<1.22.4
    - matplotlib >=3.5.3
    - gdal >=3.4.3,<3.5.1
    - pyramids >=0.2.4
    - scikit-learn >=1.1.2
    - statista >=0.1.5
    - loguru >=0.6.0

test:
  imports:
    - geostatista

about:
  home: https://github.com/MAfarrag/geostatista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Geo-spatial statistical package
  description: |
    Geo-spatial statistical package.
  dev_url: https://github.com/MAfarrag/geostatista
  doc_url: https://geostatista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/geostatista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
