{% set name = "geostatista" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/geostatista/archive/{{ version }}.tar.gz
  sha256: 22871b5a777c0ee2bab7f16af5e1c92fe02782c6fa39861e8458310a55bb9206

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=22.3.1
  run:
    - python >={{ python_min }},<3.11
    - numpy >=1.24.1
    - pip >=22.3.1
    - statista >=0.1.8
    - pyramids >=0.3.2
    - loguru >=0.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - geostatista

about:
  home: https://github.com/MAfarrag/geostatista
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Geo-spatial statistical package
  description: |
    Geo-spatial statistical package.
  dev_url: https://github.com/MAfarrag/geostatista
  doc_url: https://geostatista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/geostatista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
