{% set name = "geostatista" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/geostatista/archive/{{ version }}.tar.gz
  sha256: 9bf35177d0ebdb31487568b50144afbb442240b901515b81eaadf88807ba9759

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.15
    - pip >=22.3.1
  run:
    - python >=3.9,<3.15
    - numpy ==1.23.5
    - pip >=22.3.1
    - statista >=0.1.7
    - pyramids >=0.2.10
    - loguru >=0.6.0
    - pytest >=7.2.0
    - pytest-cov ==4.0.0

test:
  imports:
    - geostatista

about:
  home: https://github.com/MAfarrag/geostatista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Geo-spatial statistical package
  description: |
    Geo-spatial statistical package.
  dev_url: https://github.com/MAfarrag/geostatista
  doc_url: https://geostatista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/geostatista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
