{% set name = "geostatista" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/geostatista/archive/{{ version }}.tar.gz
  sha256: 896c13653fd63c4613eb6c18c1a449f829e8fa724eb5352e1f86fa9494ba0997

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9.1,<3.12
    - pip >=22.2.2
    - poetry >=1.1.15
  run:
    - python  >=3.9.1,<3.12
    - pip >=22.2.2
    - numpy >=1.21.2,<1.23.3
    - matplotlib >=3.5.3
    - gdal >=3.4.3,<3.5.1
    - scipy >=1.9.1
    - pyramids >=0.2.5
    - statista >=0.1.6
    - loguru >=0.5.3

test:
  imports:
    - geostatista

about:
  home: https://github.com/MAfarrag/geostatista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Geo-spatial statistical package
  description: |
    Geo-spatial statistical package.
  dev_url: https://github.com/MAfarrag/geostatista
  doc_url: https://geostatista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/geostatista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
